name: Bug提交
description: Bug提交
title: '[Bug]: '
body:
  - type: checkboxes
    attributes:
      label: 在提交前请确保以下这些
      options:
        - label: Easy-Reverse-Proxy为最新版本
          required: true
        - label: 在Issues找不到它
          required: true
  - type: dropdown
    attributes:
      label: 操作系统
      multiple: true
      options:
        - Linux
        - Windows
        - MacOS
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述
    validations:
      required: true