name: 功能建议
description: 功能建议
title: '[Feature]: '
body:
  - type: checkboxes
    attributes:
      label: 在提交前请确保以下这些
      options:
        - label: Easy-Reverse-Proxy为最新版本
          required: true
        - label: 在Issues找不到它
          required: true
  - type: textarea
    attributes:
      label: 描述
    validations:
      required: true